version: '3.8'

services:
  # Câu 51 & 53 & 55: Khai báo Backend Service
  backend:
    image: trangdangkhoa/mern-backend:1.0
    ports:
      - "5000:5000"
    environment:
      - PORT=5000
      - MONGO_URI=mongodb+srv://cloud-lab:cloudlab123@cluster0.dddq94r.mongodb.net/cloud-lab?appName=Cluster0
      - MONGODB_URI=mongodb+srv://cloud-lab:cloudlab123@cluster0.dddq94r.mongodb.net/cloud-lab?appName=Cluster0

  # Câu 52 & 54: Khai báo Frontend Service
  frontend:
    image: trangdangkhoa/mern-frontend:2.0
    ports:
      - "3000:3000"
    depends_on:
      - backend